modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="ntr"
version="${file.jarVersion}"
displayName="Nether Transition Remains"
authors="Renascence-Studio, Chemiofitor, Naive Ranger, GQ2529, Craft_Ziyang"
[[dependencies.ntr]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"